// Code generated by "stringer -type=GameMode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOMB-327933806]
}

const _GameMode_name = "BOMB"

var _GameMode_index = [...]uint8{0, 4}

func (i GameMode) String() string {
	i -= 327933806
	if i < 0 || i >= GameMode(len(_GameMode_index)-1) {
		return "GameMode(" + strconv.FormatInt(int64(i+327933806), 10) + ")"
	}
	return _GameMode_name[_GameMode_index[i]:_GameMode_index[i+1]]
}
