// Code generated by "stringer -type=Map"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OREGON-231702797556]
}

const _Map_name = "OREGON"

var _Map_index = [...]uint8{0, 6}

func (i Map) String() string {
	i -= 231702797556
	if i < 0 || i >= Map(len(_Map_index)-1) {
		return "Map(" + strconv.FormatInt(int64(i+231702797556), 10) + ")"
	}
	return _Map_name[_Map_index[i]:_Map_index[i+1]]
}
