// Code generated by "stringer -type=ActivityType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KILL-0]
	_ = x[DEATH-1]
	_ = x[PLANT-2]
	_ = x[DEFUSE-3]
	_ = x[LOCATE_OBJECTIVE-4]
	_ = x[BATTLEYE-5]
	_ = x[PLAYER_LEAVE-6]
}

const _ActivityType_name = "KILLDEATHPLANTDEFUSELOCATE_OBJECTIVEBATTLEYEPLAYER_LEAVE"

var _ActivityType_index = [...]uint8{0, 4, 9, 14, 20, 36, 44, 56}

func (i ActivityType) String() string {
	if i < 0 || i >= ActivityType(len(_ActivityType_index)-1) {
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActivityType_name[_ActivityType_index[i]:_ActivityType_index[i+1]]
}
