// Code generated by "stringer -type=GameMode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BOMB-327933806]
	_ = x[SECURE_AREA-1983085217]
	_ = x[HOSTAGE-2838806006]
}

const (
	_GameMode_name_0 = "BOMB"
	_GameMode_name_1 = "SECURE_AREA"
	_GameMode_name_2 = "HOSTAGE"
)

func (i GameMode) String() string {
	switch {
	case i == 327933806:
		return _GameMode_name_0
	case i == 1983085217:
		return _GameMode_name_1
	case i == 2838806006:
		return _GameMode_name_2
	default:
		return "GameMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
