// Code generated by "stringer -type=MatchType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QUICK_MATCH-1]
	_ = x[CUSTOM_GAME-7]
	_ = x[UNRANKED-12]
}

const (
	_MatchType_name_0 = "QUICK_MATCH"
	_MatchType_name_1 = "CUSTOM_GAME"
	_MatchType_name_2 = "UNRANKED"
)

func (i MatchType) String() string {
	switch {
	case i == 1:
		return _MatchType_name_0
	case i == 7:
		return _MatchType_name_1
	case i == 12:
		return _MatchType_name_2
	default:
		return "MatchType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
