// Code generated by "stringer -type=Map"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClubHouse-837214085]
	_ = x[KafeDostoyevsky-1378191338]
	_ = x[Kanal-1460220617]
	_ = x[Yacht-1767965020]
	_ = x[PresidentialPlane-2609218856]
	_ = x[Consulate-2609221242]
	_ = x[BartlettU-2697268122]
	_ = x[Coastline-42090092951]
	_ = x[Tower-53627213396]
	_ = x[Villa-88107330328]
	_ = x[Fortress-126196841359]
	_ = x[HerefordBase-127951053400]
	_ = x[ThemePark-199824623654]
	_ = x[Oregon-231702797556]
	_ = x[House-237873412352]
	_ = x[Chalet-259816839773]
	_ = x[Skyscraper-276279025182]
	_ = x[Border-305979357167]
	_ = x[Favela-329867321446]
	_ = x[Bank-355496559878]
	_ = x[Outback-362605108559]
	_ = x[EmeraldPlains-365284490964]
	_ = x[StadiumBravo-270063334510]
	_ = x[NighthavenLabs-378595635123]
}

const _Map_name = "ClubHouseKafeDostoyevskyKanalYachtPresidentialPlaneConsulateBartlettUCoastlineTowerVillaFortressHerefordBaseThemeParkOregonHouseChaletStadiumBravoSkyscraperBorderFavelaBankOutbackEmeraldPlainsNighthavenLabs"

var _Map_map = map[Map]string{
	837214085:    _Map_name[0:9],
	1378191338:   _Map_name[9:24],
	1460220617:   _Map_name[24:29],
	1767965020:   _Map_name[29:34],
	2609218856:   _Map_name[34:51],
	2609221242:   _Map_name[51:60],
	2697268122:   _Map_name[60:69],
	42090092951:  _Map_name[69:78],
	53627213396:  _Map_name[78:83],
	88107330328:  _Map_name[83:88],
	126196841359: _Map_name[88:96],
	127951053400: _Map_name[96:108],
	199824623654: _Map_name[108:117],
	231702797556: _Map_name[117:123],
	237873412352: _Map_name[123:128],
	259816839773: _Map_name[128:134],
	270063334510: _Map_name[134:146],
	276279025182: _Map_name[146:156],
	305979357167: _Map_name[156:162],
	329867321446: _Map_name[162:168],
	355496559878: _Map_name[168:172],
	362605108559: _Map_name[172:179],
	365284490964: _Map_name[179:192],
	378595635123: _Map_name[192:206],
}

func (i Map) String() string {
	if str, ok := _Map_map[i]; ok {
		return str
	}
	return "Map(" + strconv.FormatInt(int64(i), 10) + ")"
}
