// Code generated by "stringer -type=MatchUpdateType"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Kill-0]
	_ = x[Death-1]
	_ = x[DefuserPlantStart-2]
	_ = x[DefuserPlantComplete-3]
	_ = x[DefuserDisableStart-4]
	_ = x[DefuserDisableComplete-5]
	_ = x[LocateObjective-6]
	_ = x[OperatorSwap-7]
	_ = x[Battleye-8]
	_ = x[PlayerLeave-9]
	_ = x[Other-10]
}

const _MatchUpdateType_name = "KillDeathDefuserPlantStartDefuserPlantCompleteDefuserDisableStartDefuserDisableCompleteLocateObjectiveOperatorSwapBattleyePlayerLeaveOther"

var _MatchUpdateType_index = [...]uint8{0, 4, 9, 26, 46, 65, 87, 102, 114, 122, 133, 138}

func (i MatchUpdateType) String() string {
	if i < 0 || i >= MatchUpdateType(len(_MatchUpdateType_index)-1) {
		return "MatchUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchUpdateType_name[_MatchUpdateType_index[i]:_MatchUpdateType_index[i+1]]
}
