// Code generated by "stringer -type=MatchUpdateType"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KILL-0]
	_ = x[DEATH-1]
	_ = x[DEFUSER_PLANT_START-2]
	_ = x[DEFUSER_PLANT_COMPLETE-3]
	_ = x[DEFUSER_DISABLE_START-4]
	_ = x[DEFUSER_DISABLE_COMPLETE-5]
	_ = x[LOCATE_OBJECTIVE-6]
	_ = x[BATTLEYE-7]
	_ = x[PLAYER_LEAVE-8]
	_ = x[OTHER-9]
}

const _MatchUpdateType_name = "KILLDEATHDEFUSER_PLANT_STARTDEFUSER_PLANT_COMPLETEDEFUSER_DISABLE_STARTDEFUSER_DISABLE_COMPLETELOCATE_OBJECTIVEBATTLEYEPLAYER_LEAVEOTHER"

var _MatchUpdateType_index = [...]uint8{0, 4, 9, 28, 50, 71, 95, 111, 119, 131, 136}

func (i MatchUpdateType) String() string {
	if i < 0 || i >= MatchUpdateType(len(_MatchUpdateType_index)-1) {
		return "MatchUpdateType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatchUpdateType_name[_MatchUpdateType_index[i]:_MatchUpdateType_index[i+1]]
}
