// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Castle-92270642682]
	_ = x[Aruni-104189664704]
	_ = x[Kaid-161289666230]
	_ = x[Mozzie-174977508820]
	_ = x[Pulse-92270642708]
	_ = x[Ace-104189664390]
	_ = x[Echo-92270642214]
	_ = x[Azami-378305069945]
	_ = x[Solis-391752120891]
	_ = x[Capitao-92270644215]
	_ = x[Zofia-92270644189]
	_ = x[Dokkaebi-92270644267]
	_ = x[Warden-104189662920]
	_ = x[Mira-92270644319]
	_ = x[Sledge-92270642344]
	_ = x[Melusi-104189664273]
	_ = x[Bandit-92270642526]
	_ = x[Valkyrie-92270642188]
	_ = x[Rook-92270644059]
	_ = x[Kapkan-92270641980]
	_ = x[Zero-291191151607]
	_ = x[Iana-104189664038]
	_ = x[Ash-92270642656]
	_ = x[Blackbeard-92270642136]
	_ = x[Osa-288200867444]
	_ = x[Thorn-373711624351]
	_ = x[Jager-92270642604]
	_ = x[Kali-104189663920]
	_ = x[Thermite-92270642760]
	_ = x[Brava-288200866821]
	_ = x[Amaru-104189663607]
	_ = x[Ying-92270642292]
	_ = x[Lesion-92270642266]
	_ = x[Doc-92270644007]
	_ = x[Lion-104189661861]
	_ = x[Fuze-92270642032]
	_ = x[Smoke-92270642396]
	_ = x[Vigil-92270644293]
	_ = x[Mute-92270642318]
	_ = x[Goyo-104189663698]
	_ = x[Wamai-104189663803]
	_ = x[Ela-92270644163]
	_ = x[Montagne-92270644033]
	_ = x[Nokk-104189663024]
	_ = x[Alibi-104189662071]
	_ = x[Finka-104189661965]
	_ = x[Caveira-92270644241]
	_ = x[Nomad-161289666248]
	_ = x[Thunderbird-288200867351]
}

const _Operator_name = "KapkanFuzeBlackbeardValkyrieEchoLesionYingMuteSledgeSmokeBanditJagerAshCastlePulseThermiteDocMontagneRookElaZofiaCapitaoCaveiraDokkaebiVigilMiraLionFinkaAlibiWardenNokkAmaruGoyoWamaiKaliIanaMelusiAceAruniKaidNomadMozzieBravaThunderbirdOsaZeroThornAzamiSolis"

var _Operator_map = map[Operator]string{
	92270641980:  _Operator_name[0:6],
	92270642032:  _Operator_name[6:10],
	92270642136:  _Operator_name[10:20],
	92270642188:  _Operator_name[20:28],
	92270642214:  _Operator_name[28:32],
	92270642266:  _Operator_name[32:38],
	92270642292:  _Operator_name[38:42],
	92270642318:  _Operator_name[42:46],
	92270642344:  _Operator_name[46:52],
	92270642396:  _Operator_name[52:57],
	92270642526:  _Operator_name[57:63],
	92270642604:  _Operator_name[63:68],
	92270642656:  _Operator_name[68:71],
	92270642682:  _Operator_name[71:77],
	92270642708:  _Operator_name[77:82],
	92270642760:  _Operator_name[82:90],
	92270644007:  _Operator_name[90:93],
	92270644033:  _Operator_name[93:101],
	92270644059:  _Operator_name[101:105],
	92270644163:  _Operator_name[105:108],
	92270644189:  _Operator_name[108:113],
	92270644215:  _Operator_name[113:120],
	92270644241:  _Operator_name[120:127],
	92270644267:  _Operator_name[127:135],
	92270644293:  _Operator_name[135:140],
	92270644319:  _Operator_name[140:144],
	104189661861: _Operator_name[144:148],
	104189661965: _Operator_name[148:153],
	104189662071: _Operator_name[153:158],
	104189662920: _Operator_name[158:164],
	104189663024: _Operator_name[164:168],
	104189663607: _Operator_name[168:173],
	104189663698: _Operator_name[173:177],
	104189663803: _Operator_name[177:182],
	104189663920: _Operator_name[182:186],
	104189664038: _Operator_name[186:190],
	104189664273: _Operator_name[190:196],
	104189664390: _Operator_name[196:199],
	104189664704: _Operator_name[199:204],
	161289666230: _Operator_name[204:208],
	161289666248: _Operator_name[208:213],
	174977508820: _Operator_name[213:219],
	288200866821: _Operator_name[219:224],
	288200867351: _Operator_name[224:235],
	288200867444: _Operator_name[235:238],
	291191151607: _Operator_name[238:242],
	373711624351: _Operator_name[242:247],
	378305069945: _Operator_name[247:252],
	391752120891: _Operator_name[252:257],
}

func (i Operator) String() string {
	if str, ok := _Operator_map[i]; ok {
		return str
	}
	return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
}
