// Code generated by "genops.go -type=Operator"; DO NOT EDIT.
package dissect

import "errors"

type OperatorRole int

const (
	Atk OperatorRole = iota
	Def
)

var _operatorRoles = map[Operator]OperatorRole{
	104189664273: Def,
	92270642318:  Def,
	104189663607: Atk,
	104189661861: Atk,
	92270641980:  Def,
	92270644033:  Atk,
	104189664704: Def,
	104189664390: Atk,
	92270644215:  Atk,
	92270642708:  Def,
	92270642682:  Def,
	92270644267:  Atk,
	92270642344:  Atk,
	92270642214:  Def,
	92270642656:  Atk,
	92270642604:  Def,
	92270642292:  Atk,
	104189662071: Def,
	161289666248: Atk,
	92270644163:  Def,
	391752120891: Def,
	92270644319:  Def,
	373711624351: Def,
	174977508820: Def,
	92270642396:  Def,
	161289666230: Def,
	104189662920: Def,
	288200866821: Atk,
	92270642136:  Atk,
	104189663698: Def,
	104189663024: Atk,
	92270644189:  Atk,
	92270644059:  Def,
	288200867444: Atk,
	92270642526:  Def,
	92270642760:  Atk,
	92270642266:  Def,
	378305069945: Def,
	291191151607: Atk,
	288200867351: Def,
	92270642188:  Def,
	92270644293:  Def,
	92270644241:  Def,
	92270642032:  Atk,
	104189663803: Def,
	104189661965: Atk,
	92270644007:  Def,
	104189664038: Atk,
	104189663920: Atk,
}

func (i Operator) Role() (OperatorRole, error) {
	if r, ok := _operatorRoles[i]; ok {
		return r, nil
	}
	return 0, errors.New("role unknown for this operator")
}
