// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package dissect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Recruit-359656345734]
	_ = x[Castle-92270642682]
	_ = x[Aruni-104189664704]
	_ = x[Kaid-161289666230]
	_ = x[Mozzie-174977508820]
	_ = x[Pulse-92270642708]
	_ = x[Ace-104189664390]
	_ = x[Echo-92270642214]
	_ = x[Azami-378305069945]
	_ = x[Solis-391752120891]
	_ = x[Capitao-92270644215]
	_ = x[Zofia-92270644189]
	_ = x[Dokkaebi-92270644267]
	_ = x[Warden-104189662920]
	_ = x[Mira-92270644319]
	_ = x[Sledge-92270642344]
	_ = x[Melusi-104189664273]
	_ = x[Bandit-92270642526]
	_ = x[Valkyrie-92270642188]
	_ = x[Rook-92270644059]
	_ = x[Kapkan-92270641980]
	_ = x[Zero-291191151607]
	_ = x[Iana-104189664038]
	_ = x[Ash-92270642656]
	_ = x[Blackbeard-92270642136]
	_ = x[Osa-288200867444]
	_ = x[Thorn-373711624351]
	_ = x[Jager-92270642604]
	_ = x[Kali-104189663920]
	_ = x[Thermite-92270642760]
	_ = x[Brava-288200866821]
	_ = x[Amaru-104189663607]
	_ = x[Ying-92270642292]
	_ = x[Lesion-92270642266]
	_ = x[Doc-92270644007]
	_ = x[Lion-104189661861]
	_ = x[Fuze-92270642032]
	_ = x[Smoke-92270642396]
	_ = x[Vigil-92270644293]
	_ = x[Mute-92270642318]
	_ = x[Goyo-104189663698]
	_ = x[Wamai-104189663803]
	_ = x[Ela-92270644163]
	_ = x[Montagne-92270644033]
	_ = x[Nokk-104189663024]
	_ = x[Alibi-104189662071]
	_ = x[Finka-104189661965]
	_ = x[Caveira-92270644241]
	_ = x[Nomad-161289666248]
	_ = x[Thunderbird-288200867351]
	_ = x[Sens-384797789346]
	_ = x[IQ-92270642578]
	_ = x[Blitz-92270642539]
	_ = x[Hibana-92270642240]
	_ = x[Maverick-104189662384]
	_ = x[Flores-328397386974]
	_ = x[Buck-92270642474]
	_ = x[Twitch-92270644111]
	_ = x[Gridlock-174977508808]
	_ = x[Thatcher-92270642422]
	_ = x[Glaz-92270642084]
	_ = x[Jackal-92270644345]
	_ = x[Grim-374667788042]
	_ = x[Tachanka-291437347686]
	_ = x[Oryx-104189664155]
	_ = x[Frost-92270642500]
	_ = x[Maestro-104189662175]
	_ = x[Clash-104189662280]
	_ = x[Fenrir-288200867339]
	_ = x[Ram-395943091136]
	_ = x[Tubarao-288200867549]
	_ = x[Deimos-374667787816]
}

const _Operator_name = "KapkanFuzeGlazBlackbeardValkyrieEchoHibanaLesionYingMuteSledgeSmokeThatcherBuckFrostBanditBlitzIQJagerAshCastlePulseThermiteDocMontagneRookTwitchElaZofiaCapitaoCaveiraDokkaebiVigilMiraJackalLionFinkaAlibiMaestroClashMaverickWardenNokkAmaruGoyoWamaiKaliIanaOryxMelusiAceAruniKaidNomadGridlockMozzieBravaFenrirThunderbirdOsaTubaraoZeroTachankaFloresRecruitThornDeimosGrimAzamiSensSolisRam"

var _Operator_map = map[Operator]string{
	92270641980:  _Operator_name[0:6],
	92270642032:  _Operator_name[6:10],
	92270642084:  _Operator_name[10:14],
	92270642136:  _Operator_name[14:24],
	92270642188:  _Operator_name[24:32],
	92270642214:  _Operator_name[32:36],
	92270642240:  _Operator_name[36:42],
	92270642266:  _Operator_name[42:48],
	92270642292:  _Operator_name[48:52],
	92270642318:  _Operator_name[52:56],
	92270642344:  _Operator_name[56:62],
	92270642396:  _Operator_name[62:67],
	92270642422:  _Operator_name[67:75],
	92270642474:  _Operator_name[75:79],
	92270642500:  _Operator_name[79:84],
	92270642526:  _Operator_name[84:90],
	92270642539:  _Operator_name[90:95],
	92270642578:  _Operator_name[95:97],
	92270642604:  _Operator_name[97:102],
	92270642656:  _Operator_name[102:105],
	92270642682:  _Operator_name[105:111],
	92270642708:  _Operator_name[111:116],
	92270642760:  _Operator_name[116:124],
	92270644007:  _Operator_name[124:127],
	92270644033:  _Operator_name[127:135],
	92270644059:  _Operator_name[135:139],
	92270644111:  _Operator_name[139:145],
	92270644163:  _Operator_name[145:148],
	92270644189:  _Operator_name[148:153],
	92270644215:  _Operator_name[153:160],
	92270644241:  _Operator_name[160:167],
	92270644267:  _Operator_name[167:175],
	92270644293:  _Operator_name[175:180],
	92270644319:  _Operator_name[180:184],
	92270644345:  _Operator_name[184:190],
	104189661861: _Operator_name[190:194],
	104189661965: _Operator_name[194:199],
	104189662071: _Operator_name[199:204],
	104189662175: _Operator_name[204:211],
	104189662280: _Operator_name[211:216],
	104189662384: _Operator_name[216:224],
	104189662920: _Operator_name[224:230],
	104189663024: _Operator_name[230:234],
	104189663607: _Operator_name[234:239],
	104189663698: _Operator_name[239:243],
	104189663803: _Operator_name[243:248],
	104189663920: _Operator_name[248:252],
	104189664038: _Operator_name[252:256],
	104189664155: _Operator_name[256:260],
	104189664273: _Operator_name[260:266],
	104189664390: _Operator_name[266:269],
	104189664704: _Operator_name[269:274],
	161289666230: _Operator_name[274:278],
	161289666248: _Operator_name[278:283],
	174977508808: _Operator_name[283:291],
	174977508820: _Operator_name[291:297],
	288200866821: _Operator_name[297:302],
	288200867339: _Operator_name[302:308],
	288200867351: _Operator_name[308:319],
	288200867444: _Operator_name[319:322],
	288200867549: _Operator_name[322:329],
	291191151607: _Operator_name[329:333],
	291437347686: _Operator_name[333:341],
	328397386974: _Operator_name[341:347],
	359656345734: _Operator_name[347:354],
	373711624351: _Operator_name[354:359],
	374667787816: _Operator_name[359:365],
	374667788042: _Operator_name[365:369],
	378305069945: _Operator_name[369:374],
	384797789346: _Operator_name[374:378],
	391752120891: _Operator_name[378:383],
	395943091136: _Operator_name[383:386],
}

func (i Operator) String() string {
	if str, ok := _Operator_map[i]; ok {
		return str
	}
	return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
}
